# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xWq-wIaHzZilAfFQKMa1TmfchKHESkDL
"""

n = int(input("Enter a number: "))
a = n % 2
if a > 0:
    print("This is an odd number.")
else:
    print("This is an even number.")